<template>
  <div class="doc-content">
    <h1>FAQ</h1>

    <h2>⚠️ Safety Notice</h2>

    <div class="doc-warning">
      <strong>Please read carefully before using this tool.</strong>
    </div>

    <h3>How it Works</h3>
    <p>
      This tool edits local JSON files generated by the game's "Recover from Stuck" feature. It runs
      entirely locally, does not modify game memory or executables, and uploads no data.
    </p>

    <h3>Is this Officially Approved?</h3>
    <p>
      <strong>No.</strong> While the game stores data in plain text JSON and validates it on import,
      modifying these files is <strong>not explicitly officially supported</strong>.
    </p>

    <h3>Risks</h3>
    <p>Theoretical risks include:</p>
    <ul>
      <li>Data corruption or loss</li>
      <li>Scheme failing in-game review</li>
      <li>Account restrictions (though unlikely for local file edits)</li>
    </ul>
    <p class="text-sm text-muted-foreground">
      <strong>Recommendation:</strong> Backup your original files. Do not add non-existent items or
      invalid coordinates.
    </p>

    <h3>Disclaimer</h3>
    <p><strong>By using this tool, you agree that:</strong></p>
    <ul>
      <li><strong>Use at Own Risk:</strong> You assume all responsibility for any consequences.</li>
      <li><strong>Compliance:</strong> You will use the tool in accordance with local laws.</li>
      <li><strong>Personal Use Only:</strong> Not for commercial use.</li>
    </ul>

    <div class="doc-warning">
      <strong>If you are uncomfortable with these risks, please do not use this tool.</strong>
    </div>

    <h2>Data Sources</h2>

    <h3>Furniture Data</h3>
    <p>
      Furniture names and icons are provided by
      <a
        href="https://nuan5.pro"
        target="_blank"
        rel="noopener noreferrer"
        class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
      >
        NUAN5.PRO
      </a>
      . Thanks for their support!
    </p>

    <h2>Feedback</h2>
    <p>For bug reports or feature requests:</p>
    <p>
      <a
        href="https://github.com/ChanIok/BuildingMomo/issues"
        target="_blank"
        rel="noopener noreferrer"
        class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
      >
        GitHub Issues
      </a>
    </p>

    <h2>About</h2>
    <ul>
      <li>
        <strong>Motivation:</strong> Created purely out of personal interest to enhance the building
        experience.
      </li>
      <li>
        <strong>Maintenance:</strong> I will provide regular updates and maintenance as long as I
        continue playing the game.
      </li>
      <li>
        <strong>Copyright:</strong> Code is open source under the
        <a
          href="https://github.com/ChanIok/BuildingMomo/blob/main/LICENSE"
          target="_blank"
          rel="noopener noreferrer"
          class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
        >
          MIT License </a
        >. Game assets belong to the original developer.
      </li>
    </ul>

    <p class="mt-8 text-sm text-muted-foreground">Last Updated: 2025-12-06</p>
  </div>
</template>
