<template>
  <div class="doc-content">
    <h1>FAQ</h1>

    <h2>Safety Notice</h2>

    <div class="doc-warning">
      <strong>Please read carefully before using this tool.</strong>
    </div>

    <h3>How it Works</h3>
    <p>
      This tool edits local JSON files generated by the game's "Recover from Stuck" feature. It runs
      entirely locally, does not modify game memory or executables, and uploads no data.
    </p>

    <h3>Is this Officially Approved?</h3>
    <p>
      <strong>No.</strong> While the game stores data in plain text JSON and validates it on import,
      modifying these files is <strong>not explicitly officially supported</strong>.
    </p>

    <h3>Risks</h3>
    <p>Theoretical risks include:</p>
    <ul>
      <li>Data corruption or loss</li>
      <li>Scheme failing in-game review</li>
      <li>Account restrictions (though unlikely for local file edits)</li>
    </ul>
    <p class="text-sm text-muted-foreground">
      <strong>Recommendation:</strong> Back up your original scheme before use, edit data with
      caution, and avoid using out-of-range coordinates.
    </p>

    <h3>Disclaimer</h3>
    <p><strong>By using this tool, you agree that:</strong></p>
    <ul>
      <li><strong>Use at Own Risk:</strong> You assume all responsibility for any consequences.</li>
      <li><strong>Compliance:</strong> You will use the tool in accordance with local laws.</li>
      <li><strong>Personal Use Only:</strong> Not for commercial use.</li>
    </ul>

    <div class="doc-warning">
      <strong>If you are uncomfortable with these risks, please do not use this tool.</strong><br />
      This tool is designed as an interim solution for players with specific needs until official
      building tools become available.
    </div>

    <h2>Troubleshooting</h2>

    <h3>UI Shows Placeholder Text (e.g., &lt;MISSING STRING TABLE ENTRY&gt;)</h3>
    <p>
      <strong>Issue:</strong> When saving or loading schemes, the game UI displays placeholder text
      like <code>&lt;MISSING STRING TABLE ENTRY&gt;</code>.
    </p>
    <p>
      <strong>Cause:</strong> This is a known game bug, unrelated to this tool. It has been reported
      by the community and can randomly occur even during normal gameplay.
    </p>
    <p><strong>Solution:</strong></p>
    <ul>
      <li>Return to the game's login screen and re-login to restore normal display</li>
      <li>If the issue persists, report it to the game's official support team</li>
    </ul>

    <h3>Import Prompts Appear During Building</h3>
    <p>
      <strong>Issue:</strong> The editor shows "File Update Detected" import prompts even though you
      didn't manually click "Recover from Stuck."
    </p>
    <p>
      <strong>Cause:</strong> This is normal behavior. The game auto-saves building data
      periodically during construction, and the monitoring mode detects these automatic file
      changes.
    </p>
    <p><strong>What to Do:</strong></p>
    <ul>
      <li>If you're still actively building, click "Later" to dismiss the prompt</li>
      <li>
        Only import when you've intentionally clicked "Recover from Stuck" to export your complete
        scheme data
      </li>
    </ul>

    <h3>No Import Dialog After 'Recover from Stuck'</h3>
    <p>
      <strong>Issue:</strong> After clicking "Recover from Stuck" and confirming in-game, no import
      dialog appears in the editor.
    </p>
    <p><strong>Troubleshooting Steps:</strong></p>
    <ol>
      <li>Check if the top-right corner displays <strong>"Monitoring BuildData"</strong> status</li>
      <li>
        If not displayed, monitoring has stopped—re-link the game folder via
        <strong>File &gt; Link Game Folder</strong>
      </li>
      <li>
        Note: Refreshing the page or reopening the editor will reset monitoring and require
        directory re-authorization
      </li>
    </ol>
    <p class="text-sm text-muted-foreground">
      <strong>Tip:</strong> Monitoring relies on browser file system permissions, which must be
      re-granted after page refresh.
    </p>

    <h2>Data Sources</h2>

    <h3>Furniture Data</h3>
    <p>
      Furniture names and icons are provided by
      <a
        href="https://nuan5.pro"
        target="_blank"
        rel="noopener noreferrer"
        class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
      >
        NUAN5.PRO
      </a>
      . Thanks for their support!
    </p>

    <h2>Feedback</h2>
    <p>For bug reports or feature requests:</p>
    <p>
      <a
        href="https://github.com/ChanIok/BuildingMomo/issues"
        target="_blank"
        rel="noopener noreferrer"
        class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
      >
        GitHub Issues
      </a>
    </p>

    <h2>About</h2>
    <ul>
      <li>
        <strong>Motivation:</strong> The official editor was driving me crazy. Instead of waiting, I
        built this.
      </li>
      <li>
        <strong>Maintenance:</strong> I'll keep this updated as long as I'm still playing the game.
      </li>
      <li>
        <strong>Copyright:</strong> Code is open source under the
        <a
          href="https://github.com/ChanIok/BuildingMomo/blob/main/LICENSE"
          target="_blank"
          rel="noopener noreferrer"
          class="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
        >
          MIT License </a
        >. Game assets belong to the original developer.
      </li>
    </ul>

    <p class="mt-8 text-sm text-muted-foreground">Last Updated: 2025-12-11</p>
  </div>
</template>
